In [6]:
import pandas as pd
import random
import faker

In [11]:
# titles, authors, genres
titles = ["Shadows of Tomorrow", "Whispers of the Past", "Echoes of the Sea", "Dreams of Stardust",
          "Secrets of the Forest", "Legends of the Sky", "Mysteries of the Deep", "Glimpses of Dawn",
          "Fragments of the Night", "Journeys to the Unknown", "Tales of the Brave", "Chronicles of the Lost",
          "Sagas of the Wild", "Memories of the Ancient", "Visions of the Future", "Paths of Destiny",
          "Voices of the Wind", "Reflections of the Moon", "Guardians of the Realm", "Sorrows of the Heart",
          "Flames of Rebellion", "Songs of the Earth", "Dances with Shadows", "Traces of Light", "Echoes of Silence",
          "Whispers of Time", "Shadows of Fate", "Dreams Unseen", "Secrets Unspoken", "Legends Unwritten",
          "Mysteries Uncovered", "Glimpses Unveiled", "Fragments Unbound", "Journeys Uncharted", "Tales Untold",
          "Chronicles Unfolding", "Sagas Unraveling", "Memories Unearthed", "Visions Unleashed", "Paths Unveiled",
          "Voices Unheard", "Reflections Unseen", "Guardians Unleashed", "Sorrows Unshared", "Flames Unquenched",
          "Songs Unending", "Dances Unstoppable", "Traces Untraceable", "Echoes Unheard", "Whispers Unanswered"]
authors = ["Alexa Jordan", "Blake Morrison", "Charlie Phoenix", "Dakota Lee", "Evelyn Woods", "Finley Rivera",
           "Grayson Knight", "Harper Ellis", "Isaiah Clarke", "Jordan Hayes", "Kai Taylor", "Landon Carter",
           "Mason Brooks", "Nolan Foster", "Olivia Bennett", "Peyton Walsh", "Quinn Edwards", "Riley Adams",
           "Skyler Morgan", "Taylor Gibson", "Ulysses Grant", "Violet Shaw", "Weston Bailey", "Xander Reed",
           "Yasmin Ali", "Zachary Turner", "Avery Smith", "Bailey Johnson", "Carter Davis", "Danielle Brown"]
genres = ["Fantasy", "Science Fiction", "Mystery", "Thriller", "Romance", "Historical Fiction", "Young Adult"]

# Function to generate a random ISBN
def generate_isbn():
    return f'{random.randint(100, 999)}-{random.randint(100, 999)}-{random.randint(100, 999)}-{random.randint(10, 99)}'

# generating the dataset
data = []
for i in range(50):
    book = {
        "Title": random.choice(titles),
        "Author": random.choice(authors),
        "Genre": random.choice(genres),
        "Publication Year": random.randint(1980, 2023),
        "ISBN": generate_isbn(),
        "Fake Amazon Link": f"https://www.amazon.fake/book/{i+1}"
    }
    data.append(book)

df_books = pd.DataFrame(data)
df_books.head()

In [ ]:
df_books.to_csv('/Users/justinsheng/Downloads/books.csv', index=False)

In [7]:
fake = faker.Faker()

# genres
genres = ["Fantasy", "Science Fiction", "Mystery", "Thriller", "Romance", "Historical Fiction", "Young Adult"]

# generating random genre preferences
def generate_genre_preferences():
    num_genres = random.randint(0, 3) 
    if num_genres == 0:
        return None  
    return ', '.join(random.sample(genres, num_genres))

# generating data for 100 users
data = []
for user_id in range(1, 101):
    user_data = {
        "User ID": user_id,
        "User Name": fake.user_name(),
        "Email": fake.email(),
        "Registration Date": fake.date_between(start_date="-5y", end_date="today"),
        "Genre Preferences": generate_genre_preferences()
    }
    data.append(user_data)

df_users = pd.DataFrame(data)
df_users.head()

,User ID,User Name,Email,Registration Date,Genre Preferences
0,1,alexandriaperez,lindaoneal@example.net,2021-04-06,Mystery
1,2,bradwallace,andrew83@example.com,2022-11-19,"Fantasy, Thriller"
2,3,kyle41,clopez@example.com,2023-04-22,Historical Fiction
3,4,mckeelisa,parkeranita@example.net,2023-08-21,"Young Adult, Romance, Fantasy"
4,5,kimberlypowers,odavis@example.com,2020-08-10,"Mystery, Romance"

In [12]:
df_users.to_csv('/Users/justinsheng/Downloads/users.csv', index=False)

In [15]:
# generating random ratings and reviews
def generate_rating_and_review():
    rating = random.randint(1, 5)

    if random.choice([True, False]):
        review = fake.sentence(nb_words=10)
    else:
        review = None  
    return rating, review

# generating 500 ratings and reviews again with the corrected function
data = []
for _ in range(500):

    user = df_users.sample().iloc[0]
    book = df_books.sample().iloc[0]


    rating, review = generate_rating_and_review()


    data.append({
        "User ID": user['User ID'],
        "User Name": user['User Name'],
        "Title": book['Title'],
        "Author": book['Author'],
        "Genre": book['Genre'],
        "Publication Year": book['Publication Year'],
        "ISBN": book['ISBN'],
        "Rating": rating,
        "Review": review
    })


df_ratings_reviews = pd.DataFrame(data)
df_ratings_reviews.head()

,User ID,User Name,Title,Author,Genre,Publication Year,ISBN,Rating,Review
0,6,vthomas,Mysteries of the Deep,Charlie Phoenix,Fantasy,1992,877-422-480-69,5,Religious part none hot board him way whose co...
1,31,daniellesherman,Dances with Shadows,Zachary Turner,Mystery,2013,442-744-512-76,2,Describe thus reduce meeting western road data.
2,91,matapenny,Guardians Unleashed,Olivia Bennett,Mystery,2009,978-445-768-30,1,Chance current task dream much within play hap...
3,22,ashleyhorne,Glimpses Unveiled,Violet Shaw,Romance,2000,737-145-898-92,1,None
4,7,krobinson,Dances with Shadows,Xander Reed,Thriller,1983,782-750-241-34,1,Water consider hot edge reach either program t...

In [17]:
df_ratings_reviews.to_csv('/Users/justinsheng/Downloads/ratings_reviews.csv', index=False)

In [19]:
# generating random browsing time and favorite status
def generate_browsing_data():
    browsing_time = random.randint(1, 600)  # Random browsing time between 1 to 600
    favorite = random.choice([0, 1])  # Randomly choose 0 or 1 for favorite
    return browsing_time, favorite

# generating 500 browsing history entries
browsing_data = []
for _ in range(500):

    user = df_users.sample().iloc[0]
    book = df_books.sample().iloc[0]


    browsing_time, favorite = generate_browsing_data()


    browsing_data.append({
        "User ID": user['User ID'],
        "User Name": user['User Name'],
        "Title": book['Title'],
        "Author": book['Author'],
        "Genre": book['Genre'],
        "Publication Year": book['Publication Year'],
        "ISBN": book['ISBN'],
        "Favorite": favorite,
        "Browsing Time": browsing_time
    })


df_browsing_history = pd.DataFrame(browsing_data)
df_browsing_history.head()

,User ID,User Name,Title,Author,Genre,Publication Year,ISBN,Favorite,Browsing Time
0,34,vmann,Mysteries Uncovered,Olivia Bennett,Romance,1996,498-957-722-68,1,265
1,48,suttonpatrick,Traces Untraceable,Charlie Phoenix,Historical Fiction,2002,217-161-634-28,1,226
2,39,williammcneil,Flames of Rebellion,Jordan Hayes,Young Adult,1990,500-132-424-66,0,586
3,27,wmoyer,Glimpses Unveiled,Violet Shaw,Romance,2000,737-145-898-92,1,339
4,69,marissamcgee,Whispers of the Past,Taylor Gibson,Young Adult,2001,835-936-189-34,0,364

In [20]:
df_browsing_history.to_csv('/Users/justinsheng/Downloads/browsing_history.csv', index=False)

In [21]:
# generating a fake introduction for each book
def generate_book_introduction(title, genre):
    introduction = f"{title} is a compelling {genre} novel that enthralls readers with its unique blend of intrigue and narrative depth. Set in an intricately designed world, the story weaves together themes of adventure, mystery, and the timeless struggle of good versus evil. This book promises to captivate from the first page to the last."
    return introduction

# Adding introductions to each book in the DataFrame
df_books['Introduction'] = df_books.apply(lambda row: generate_book_introduction(row['Title'], row['Genre']), axis=1)

# Display the first few rows of the updated DataFrame
df_books.head()

,Title,Author,Genre,Publication Year,ISBN,Fake Amazon Link,Introduction
0,Traces Untraceable,Mason Brooks,Mystery,1991,631-279-746-22,https://www.amazon.fake/book/1,Traces Untraceable is a compelling Mystery nov...
1,Flames of Rebellion,Jordan Hayes,Young Adult,1990,500-132-424-66,https://www.amazon.fake/book/2,Flames of Rebellion is a compelling Young Adul...
2,Sagas of the Wild,Landon Carter,Historical Fiction,1993,804-271-958-66,https://www.amazon.fake/book/3,Sagas of the Wild is a compelling Historical F...
3,Whispers of the Past,Xander Reed,Science Fiction,2007,780-732-505-10,https://www.amazon.fake/book/4,Whispers of the Past is a compelling Science F...
4,Voices Unheard,Taylor Gibson,Young Adult,2014,311-739-832-62,https://www.amazon.fake/book/5,Voices Unheard is a compelling Young Adult nov...

In [23]:
df_books.to_csv('/Users/justinsheng/Downloads/books_intro.csv', index=False)

In [25]:
# creating a data dictionary for the books table
data_dictionary_books = {
    "Column Name": df_books.columns,
    "Data Type": [df_books[col].dtype for col in df_books.columns],
    "Description": [
        "The title of the book.",
        "The author of the book.",
        "The genre of the book.",
        "The year the book was published.",
        "The International Standard Book Number, a unique identifier for the book.",
        "A fake link to the book's page on Amazon.",
        "A brief introduction to the book, describing its theme and narrative style."
    ]
}

df_data_dictionary_books = pd.DataFrame(data_dictionary_books)

In [26]:
df_data_dictionary_books.to_csv('/Users/justinsheng/Downloads/books_intro_dict.csv', index=False)

In [27]:
# creating a data dictionary for the browsing history table
browsing_data_dict = {
    "Column Name": df_browsing_history.columns,
    "Data Type": [df_browsing_history[col].dtype for col in df_browsing_history.columns],
    "Description": [
        "Unique identifier for the user.",
        "The name of the user.",
        "The title of the browsed book.",
        "The author of the browsed book.",
        "The genre of the browsed book.",
        "The year the book was published.",
        "The International Standard Book Number of the browsed book.",
        "Indicator of whether the user marked the book as a favorite (1 for yes, 0 for no).",
        "The time spent browsing the book in seconds."
    ]
}

df_browsing_data_dict = pd.DataFrame(browsing_data_dict)

In [28]:
df_browsing_data_dict.to_csv('/Users/justinsheng/Downloads/browsing_data_dict.csv', index=False)

In [29]:
# creating a data dictionary for the ratings and reviews table
ratings_reviews_dict = {
    "Column Name": df_ratings_reviews.columns,
    "Data Type": [df_ratings_reviews[col].dtype for col in df_ratings_reviews.columns],
    "Description": [
        "Unique identifier for the user.",
        "The name of the user.",
        "The title of the rated and reviewed book.",
        "The author of the rated and reviewed book.",
        "The genre of the rated and reviewed book.",
        "The year the book was published.",
        "The International Standard Book Number of the rated and reviewed book.",
        "The rating given to the book by the user, on a scale of 1 to 5.",
        "The review written by the user for the book, if any."
    ]
}


ratings_reviews_dict = pd.DataFrame(ratings_reviews_dict)

In [31]:
ratings_reviews_dict.to_csv('/Users/justinsheng/Downloads/ratings_reviews_dict.csv', index=False)

In [32]:
# creating a data dictionary for the users table
users_dict = {
    "Column Name": df_users.columns,
    "Data Type": [df_users[col].dtype for col in df_users.columns],
    "Description": [
        "Unique identifier for the user.",
        "The name of the user.",
        "The email address of the user.",
        "The date when the user registered.",
        "The genre preferences of the user, if any."
    ]
}

# Convert the data dictionary to a DataFrame for better visualization
users_dict = pd.DataFrame(users_dict)

In [33]:
users_dict.to_csv('/Users/justinsheng/Downloads/users_dict.csv', index=False)

In [40]:
# New set of numbers
new_numbers = [282, 4291, 263, 208, 74, 195, 68]

# New target number
new_target = 4568

# Using itertools.product to generate all combinations of +1 and -1
new_combinations = product([-1, 1], repeat=len(new_numbers))

# Attempting to find a combination that sums up to the new target
new_solution_found = False
for combo in new_combinations:
    result = sum(n * c for n, c in zip(new_numbers, combo))
    if abs(result - new_target) < 1e-6:  # Allowing a small error margin for floating point numbers
        new_solution = combo
        new_solution_found = True
        break

if new_solution_found:
    # Creating the equation from the found solution
    new_equation = " + ".join(f"{n * c}" for n, c in zip(new_numbers, new_solution) if c > 0)
    new_equation += " - " + " - ".join(f"{abs(n * c)}" for n, c in zip(new_numbers, new_solution) if c < 0)
    new_equation += f" = {new_target}"
else:
    new_equation = "No solution found with the given numbers."

new_equation

'No solution found with the given numbers.'

In [39]:
# New set of given numbers
numbers = [267, 4282, 261, 202, 65, 192, 69]

# New target number
target = 4548

# Finding a combination of operations (addition or subtraction) to reach the new target number
combinations = product([-1, 1], repeat=len(numbers))

# Trying each combination to see if it reaches the target
solution_found = False
for combo in combinations:
    result = sum(n * c for n, c in zip(numbers, combo))
    if abs(result - target) < 1e-6:  # Allowing a small error margin
        solution = combo
        solution_found = True
        break

if solution_found:
    # Creating the equation
    equation = " + ".join(f"{n * c}" for n, c in zip(numbers, solution) if c > 0)
    equation += " - " + " - ".join(f"{abs(n * c)}" for n, c in zip(numbers, solution) if c < 0)
    equation += f" = {target}"
else:
    equation = "No solution found with the given numbers."

equation

'267 + 4282 + 202 + 192 - 261 - 65 - 69 = 4548'